deployment:
  tasks:
    - export DEPLOY_PATH=/home3/clicuhac/public_html
    - /bin/rsync -a --no-perms --omit-dir-times --exclude '.git' --exclude '.cpanel.yml' --exclude 'README.md' --exclude '.well-known' --exclude 'cgi-bin' --exclude 'logs' --exclude 'index.php' ./ $DEPLOY_PATH/




