deployment:
  tasks:
    - export DEPLOY_PATH=/home3/clicuhac/public_html
    - /bin/rsync -a \
        --exclude '.git' \
        --exclude '.cpanel.yml' \
        --exclude 'README.md' \
        ./ $DEPLOY_PATH/

