<?php
declare(strict_types=1);
require_once __DIR__.'/config.php';
require_once __DIR__.'/lib/avatar.php';
require_once __DIR__.'/lib/audit.php';
if(empty($_SESSION['user_id'])){header('Location: /login.php');exit;}
$uid=(int)$_SESSION['user_id'];if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals((string)$_SESSION['csrf_token'],(string)($_POST['csrf_token']??''))){http_response_code(403);exit('Невірний токен форми');}
 $id=(int)($_POST['id']??0);
 if($id>0){$s=$pdo->prepare('SELECT title FROM nicknames WHERE id=? AND user_id=? AND deleted_at IS NOT NULL');$s->execute([$id,$uid]);$title=$s->fetchColumn();if($title!==false){$u=$pdo->prepare('UPDATE nicknames SET deleted_at=NULL WHERE id=? AND user_id=? AND deleted_at IS NOT NULL');$u->execute([$id,$uid]);if($u->rowCount()>0){audit_log($pdo,$uid,'clicuha_restore','clicuha_id='.$id.'; title='.(string)$title);$_SESSION['archive_flash']='Клікуху відновлено.';}}}
 header('Location: /my_archive.php');exit;
}
$stmt=$pdo->prepare('SELECT id,title,slug,description,avatar_path,deleted_at FROM nicknames WHERE user_id=? AND deleted_at IS NOT NULL ORDER BY deleted_at DESC');$stmt->execute([$uid]);$items=$stmt->fetchAll(PDO::FETCH_ASSOC);$flash=(string)($_SESSION['archive_flash']??'');unset($_SESSION['archive_flash']);
?><!doctype html><html lang="<?=h($lang)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Мій архів · Clicuha</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"><link rel="stylesheet" href="/assets/css/sema.css?v=123"><style>body{background:#f4f5f9}.archive-card{background:#fff;border:1px solid rgba(0,0,0,.06);border-radius:16px;padding:18px}.avatar{width:64px;height:64px;object-fit:cover;border-radius:14px;background:#eee}.avatar-empty{width:64px;height:64px;border-radius:14px;background:#eee;display:grid;place-items:center;color:#999}</style></head><body><?php require __DIR__.'/partials/navbar.php';?><main class="container py-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">Мій архів</h1><div class="text-secondary">Архівовані клікухи залишаються вашими.</div></div><a class="btn btn-outline-secondary" href="/cabinet.php">← Кабінет</a></div><?php if($flash):?><div class="alert alert-success"><?=h($flash)?></div><?php endif;?><?php if(!$items):?><div class="archive-card text-secondary">Архів порожній.</div><?php else:?><div class="row g-3"><?php foreach($items as $n):$avatar=clicuha_avatar_url($n['avatar_path']??null);?><div class="col-12 col-lg-6"><section class="archive-card h-100"><div class="d-flex gap-3"><?php if($avatar):?><img class="avatar" src="<?=h($avatar)?>" alt=""><?php else:?><div class="avatar-empty">—</div><?php endif;?><div class="flex-grow-1"><h2 class="h5 mb-1"><?=h($n['title'])?></h2><?php if($n['slug']):?><div class="small text-secondary mb-2">@<?=h($n['slug'])?></div><?php endif;?><div class="small text-secondary mb-3">В архіві з <?=h(date('d.m.Y H:i',strtotime((string)$n['deleted_at'])))?></div><form method="post" onsubmit="return confirm('Відновити цю клікуху?');"><input type="hidden" name="csrf_token" value="<?=h($_SESSION['csrf_token'])?>"><input type="hidden" name="id" value="<?=(int)$n['id']?>"><button class="btn btn-sm btn-outline-success">Відновити</button></form></div></div></section></div><?php endforeach;?></div><?php endif;?></main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html>