<?php
declare(strict_types=1);
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../lib/auth.php';
$admin=require_admin($pdo);
$q=trim((string)($_GET['q']??''));$action=trim((string)($_GET['action']??''));
$actions=$pdo->query("SELECT DISTINCT action FROM logs WHERE action IS NOT NULL AND action<>'' ORDER BY action")->fetchAll(PDO::FETCH_COLUMN);
$where=[];$params=[];
if($q!==''){$where[]="(l.details LIKE :details OR l.ip LIKE :ip OR u.email LIKE :email OR u.username LIKE :username OR CAST(l.user_id AS CHAR) LIKE :uid)";$needle='%'.$q.'%';$params=[':details'=>$needle,':ip'=>$needle,':email'=>$needle,':username'=>$needle,':uid'=>$needle];}
if($action!=='' && in_array($action,$actions,true)){$where[]='l.action=:action';$params[':action']=$action;}
$sql="SELECT l.id,l.user_id,l.action,l.details,l.ip,l.created_at,u.email,u.username FROM logs l LEFT JOIN users u ON u.id=l.user_id";
if($where)$sql.=' WHERE '.implode(' AND ',$where);$sql.=' ORDER BY l.created_at DESC,l.id DESC LIMIT 300';
$stmt=$pdo->prepare($sql);$stmt->execute($params);$logs=$stmt->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html lang="<?=h($lang)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Logs · Clicuha Admin</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"><style>
:root{--admin-side:#17151d;--admin-bg:#f4f3f7;--admin-lav:#cba3f7}body{margin:0;background:var(--admin-bg);color:#222}.admin-layout{min-height:100vh;display:grid;grid-template-columns:230px 1fr}.admin-sidebar{background:var(--admin-side);color:#fff;padding:24px 18px;display:flex;flex-direction:column;min-height:100vh}.admin-brand{color:#fff;font-weight:800;font-size:1.2rem;text-decoration:none;margin-bottom:30px}.admin-brand span{color:var(--admin-lav);font-size:.75rem;margin-left:4px}.admin-nav{display:grid;gap:8px}.admin-nav a,.admin-nav span{color:#d7d3dc;text-decoration:none;padding:10px 12px;border-radius:10px}.admin-nav a.active{color:#17151d;background:var(--admin-lav);font-weight:700}.admin-sidebar-bottom{margin-top:auto;display:grid;gap:8px}.admin-sidebar-bottom a{color:#cfcad5;text-decoration:none;font-size:.9rem}.admin-main{padding:32px}.panel{background:#fff;border-radius:16px;box-shadow:0 8px 22px rgba(26,18,37,.06);padding:22px}.details{max-width:430px;white-space:normal;word-break:break-word}.table>:not(caption)>*>*{padding:.75rem .55rem}@media(max-width:800px){.admin-layout{grid-template-columns:1fr}.admin-sidebar{min-height:auto}.admin-main{padding:20px}}
</style></head><body><div class="admin-layout"><?php $adminSection='logs';require __DIR__.'/../partials/admin_sidebar.php';?><main class="admin-main"><div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3 mb-1">Logs</h1><div class="text-secondary">Системний аудит · показано <?=count($logs)?></div></div><div class="text-end small text-secondary"><strong><?=h(($admin['username']??'')?:$admin['email'])?></strong><br>administrator</div></div><section class="panel"><form class="row g-2 mb-3" method="get"><div class="col-md-6"><input class="form-control" name="q" value="<?=h($q)?>" placeholder="Пошук: користувач, email, IP, details"></div><div class="col-md-3"><select class="form-select" name="action"><option value="">Усі дії</option><?php foreach($actions as $a):?><option value="<?=h((string)$a)?>" <?=$action===$a?'selected':''?>><?=h((string)$a)?></option><?php endforeach;?></select></div><div class="col-md-auto"><button class="btn btn-dark">Знайти</button></div><?php if($q!==''||$action!==''):?><div class="col-md-auto"><a class="btn btn-outline-secondary" href="/admin/logs.php">Очистити</a></div><?php endif;?></form><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>ID</th><th>User</th><th>Action</th><th>Details</th><th>IP</th><th>Date / time</th></tr></thead><tbody><?php foreach($logs as $row):?><tr><td class="small"><?=(int)$row['id']?></td><td><?php if(!empty($row['username'])||!empty($row['email'])):?><strong><?=h(($row['username']??'')?:$row['email'])?></strong><?php if(!empty($row['username'])&&!empty($row['email'])):?><div class="small text-secondary"><?=h($row['email'])?></div><?php endif;?><div class="small text-secondary">ID <?=(int)$row['user_id']?></div><?php else:?><span class="text-secondary">ID <?=(int)$row['user_id']?></span><?php endif;?></td><td><span class="badge text-bg-light"><?=h((string)$row['action'])?></span></td><td class="small details"><?=h((string)$row['details'])?></td><td class="small"><?=h((string)$row['ip'])?></td><td class="small text-secondary"><?=h((string)$row['created_at'])?></td></tr><?php endforeach;?><?php if(!$logs):?><tr><td colspan="6" class="text-center text-secondary py-4">Нічого не знайдено.</td></tr><?php endif;?></tbody></table></div></section></main></div></body></html>