<?php
declare(strict_types=1);
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../lib/auth.php';
$admin=require_admin($pdo);
$q=trim((string)($_GET['q']??''));
$where='';$params=[];
if($q!==''){$where='WHERE u.email LIKE :q_email OR u.username LIKE :q_username';$needle='%'.$q.'%';$params=[':q_email'=>$needle,':q_username'=>$needle];}
$sql="SELECT u.id,u.email,u.username,u.role,u.created_at,u.last_login,
COUNT(n.id) total_clicuhas,
SUM(CASE WHEN n.id IS NOT NULL AND n.deleted_at IS NULL THEN 1 ELSE 0 END) active_clicuhas,
SUM(CASE WHEN n.id IS NOT NULL AND n.deleted_at IS NOT NULL THEN 1 ELSE 0 END) archived_clicuhas
FROM users u LEFT JOIN nicknames n ON n.user_id=u.id $where
GROUP BY u.id,u.email,u.username,u.role,u.created_at,u.last_login
ORDER BY u.created_at DESC LIMIT 200";
$stmt=$pdo->prepare($sql);$stmt->execute($params);$users=$stmt->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html lang="<?=h($lang)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Users · Clicuha Admin</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"><style>
:root{--admin-side:#17151d;--admin-bg:#f4f3f7;--admin-lav:#cba3f7}body{margin:0;background:var(--admin-bg);color:#222}.admin-layout{min-height:100vh;display:grid;grid-template-columns:230px 1fr}.admin-sidebar{background:var(--admin-side);color:#fff;padding:24px 18px;display:flex;flex-direction:column;min-height:100vh}.admin-brand{color:#fff;font-weight:800;font-size:1.2rem;text-decoration:none;margin-bottom:30px}.admin-brand span{color:var(--admin-lav);font-size:.75rem;margin-left:4px}.admin-nav{display:grid;gap:8px}.admin-nav a,.admin-nav span{color:#d7d3dc;text-decoration:none;padding:10px 12px;border-radius:10px}.admin-nav a.active{color:#17151d;background:var(--admin-lav);font-weight:700}.admin-sidebar-bottom{margin-top:auto;display:grid;gap:8px}.admin-sidebar-bottom a{color:#cfcad5;text-decoration:none;font-size:.9rem}.admin-main{padding:32px}.panel{background:#fff;border-radius:16px;box-shadow:0 8px 22px rgba(26,18,37,.06);padding:22px}.table>:not(caption)>*>*{padding:.8rem .55rem}@media(max-width:800px){.admin-layout{grid-template-columns:1fr}.admin-sidebar{min-height:auto}.admin-main{padding:20px}}
</style></head><body><div class="admin-layout"><?php $adminSection='users';require __DIR__.'/../partials/admin_sidebar.php';?><main class="admin-main"><div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="h3 mb-1">Users</h1><div class="text-secondary">Користувачі Clicuha · показано <?=count($users)?></div></div><div class="text-end small text-secondary"><strong><?=h(($admin['username']??'')?:$admin['email'])?></strong><br>administrator</div></div><section class="panel"><form class="row g-2 mb-3"><div class="col-md-8"><input class="form-control" name="q" value="<?=h($q)?>" placeholder="Пошук: username або email"></div><div class="col-md-auto"><button class="btn btn-dark">Знайти</button></div><?php if($q!==''):?><div class="col-md-auto"><a class="btn btn-outline-secondary" href="/admin/users.php">Очистити</a></div><?php endif;?></form><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>User</th><th>Role</th><th>Clicuhas</th><th>Registered</th><th>Last login</th><th></th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><a class="text-decoration-none text-dark" href="/admin/user.php?id=<?=(int)$u['id']?>"><strong><?=h(($u['username']??'')?:'—')?></strong></a><div class="small text-secondary"><?=h($u['email'])?></div><div class="small text-secondary">ID <?=(int)$u['id']?></div></td><td><?php if($u['role']==='admin'):?><span class="badge" style="background:#cba3f7;color:#17151d">admin</span><?php else:?><span class="badge text-bg-light">user</span><?php endif;?></td><td><strong><?=(int)$u['total_clicuhas']?></strong><div class="small text-secondary"><?=(int)$u['active_clicuhas']?> active · <?=(int)$u['archived_clicuhas']?> archive</div></td><td class="small text-secondary"><?=h((string)$u['created_at'])?></td><td class="small text-secondary"><?=!empty($u['last_login'])?h((string)$u['last_login']):'—'?></td><td class="text-end"><a class="btn btn-sm btn-outline-dark" href="/admin/user.php?id=<?=(int)$u['id']?>">Profile</a> <?php if((int)$u['total_clicuhas']>0):?><a class="btn btn-sm btn-outline-secondary" href="/admin/nicknames.php?q=<?=urlencode((string)$u['email'])?>">Clicuhas</a><?php endif;?></td></tr><?php endforeach;?><?php if(!$users):?><tr><td colspan="6" class="text-center text-secondary py-4">Нічого не знайдено.</td></tr><?php endif;?></tbody></table></div></section></main></div></body></html>