<?php
declare(strict_types=1);
require_once __DIR__.'/../config.php';
require_once __DIR__.'/../lib/auth.php';
$admin=require_admin($pdo);
$id=(int)($_GET['id']??0);
if($id<=0){http_response_code(400);exit('Invalid user id');}
$stmt=$pdo->prepare('SELECT id,email,username,role,created_at,last_login FROM users WHERE id=? LIMIT 1');$stmt->execute([$id]);$user=$stmt->fetch(PDO::FETCH_ASSOC);if(!$user){http_response_code(404);exit('User not found');}
$ns=$pdo->prepare('SELECT id,title,slug,is_anonymous,avatar_path,created_at,deleted_at FROM nicknames WHERE user_id=? ORDER BY created_at DESC LIMIT 200');$ns->execute([$id]);$nicknames=$ns->fetchAll(PDO::FETCH_ASSOC);
$ls=$pdo->prepare('SELECT id,action,details,ip,created_at FROM logs WHERE user_id=? ORDER BY created_at DESC,id DESC LIMIT 100');$ls->execute([$id]);$logs=$ls->fetchAll(PDO::FETCH_ASSOC);
$active=0;$archived=0;foreach($nicknames as $n){if(empty($n['deleted_at']))$active++;else$archived++;}
?>
<!doctype html><html lang="<?=h($lang)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>User · Clicuha Admin</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"><style>
:root{--admin-side:#17151d;--admin-bg:#f4f3f7;--admin-lav:#cba3f7}body{margin:0;background:var(--admin-bg);color:#222}.admin-layout{min-height:100vh;display:grid;grid-template-columns:230px 1fr}.admin-sidebar{background:var(--admin-side);color:#fff;padding:24px 18px;display:flex;flex-direction:column;min-height:100vh}.admin-brand{color:#fff;font-weight:800;font-size:1.2rem;text-decoration:none;margin-bottom:30px}.admin-brand span{color:var(--admin-lav);font-size:.75rem;margin-left:4px}.admin-nav{display:grid;gap:8px}.admin-nav a,.admin-nav span{color:#d7d3dc;text-decoration:none;padding:10px 12px;border-radius:10px}.admin-nav a.active{color:#17151d;background:var(--admin-lav);font-weight:700}.admin-sidebar-bottom{margin-top:auto;display:grid;gap:8px}.admin-sidebar-bottom a{color:#cfcad5;text-decoration:none;font-size:.9rem}.admin-main{padding:32px}.panel{background:#fff;border-radius:16px;box-shadow:0 8px 22px rgba(26,18,37,.06);padding:22px}.stat{background:#f7f5fa;border-radius:12px;padding:14px}.table>:not(caption)>*>*{padding:.7rem .5rem}.details{max-width:420px;white-space:normal;word-break:break-word}@media(max-width:800px){.admin-layout{grid-template-columns:1fr}.admin-sidebar{min-height:auto}.admin-main{padding:20px}}
</style></head><body><div class="admin-layout"><?php $adminSection='users';require __DIR__.'/../partials/admin_sidebar.php';?><main class="admin-main"><div class="d-flex justify-content-between align-items-start mb-4"><div><a class="small text-decoration-none" href="/admin/users.php">← Users</a><h1 class="h3 mt-2 mb-1"><?=h(($user['username']??'')?:$user['email'])?></h1><div class="text-secondary"><?=h($user['email'])?> · ID <?=(int)$user['id']?></div></div><div class="text-end small text-secondary"><strong><?=h(($admin['username']??'')?:$admin['email'])?></strong><br>administrator</div></div>
<section class="panel mb-4"><div class="row g-3"><div class="col-md-3"><div class="stat"><div class="small text-secondary">Role</div><strong><?=h($user['role'])?></strong></div></div><div class="col-md-3"><div class="stat"><div class="small text-secondary">Registered</div><strong><?=h((string)$user['created_at'])?></strong></div></div><div class="col-md-3"><div class="stat"><div class="small text-secondary">Last login</div><strong><?=!empty($user['last_login'])?h((string)$user['last_login']):'—'?></strong></div></div><div class="col-md-3"><div class="stat"><div class="small text-secondary">Clicuhas</div><strong><?=count($nicknames)?> · <?=$active?> active · <?=$archived?> archive</strong></div></div></div></section>
<section class="panel mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Clicuhas</h2><a class="btn btn-sm btn-outline-secondary" href="/admin/nicknames.php?q=<?=urlencode((string)$user['email'])?>">Open filtered list</a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Clicuha</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody><?php foreach($nicknames as $n):?><tr><td><strong><?=h($n['title'])?></strong><?php if(!empty($n['slug'])):?><div class="small text-secondary">@<?=h($n['slug'])?></div><?php endif;?><?php if(!empty($n['is_anonymous'])):?><span class="badge text-bg-light">anonymous</span><?php endif;?></td><td><?php if(!empty($n['deleted_at'])):?><span class="badge text-bg-secondary">Archive</span><?php else:?><span class="badge text-bg-success">Active</span><?php endif;?></td><td class="small text-secondary"><?=h((string)$n['created_at'])?></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="/view.php?id=<?=(int)$n['id']?>">View</a></td></tr><?php endforeach;?><?php if(!$nicknames):?><tr><td colspan="4" class="text-center text-secondary py-4">У користувача ще немає клікух.</td></tr><?php endif;?></tbody></table></div></section>
<section class="panel"><h2 class="h5 mb-3">Activity log</h2><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Action</th><th>Details</th><th>IP</th><th>Date / time</th></tr></thead><tbody><?php foreach($logs as $l):?><tr><td><span class="badge text-bg-light"><?=h((string)$l['action'])?></span></td><td class="small details"><?=h((string)$l['details'])?></td><td class="small"><?=h((string)$l['ip'])?></td><td class="small text-secondary"><?=h((string)$l['created_at'])?></td></tr><?php endforeach;?><?php if(!$logs):?><tr><td colspan="4" class="text-center text-secondary py-4">Журнал користувача порожній.</td></tr><?php endif;?></tbody></table></div></section></main></div></body></html>